- app/src/main/res/xml/grayscale_icon_map.xml
MiXplorer v6.57.1-API26-RC from Xda has “com.mixplorer” package name
> Link MiXplorer icon to “com.mixplorer” package

- app/src/main/res/xml/grayscale_icon_map.xml
* com.oppo.camera is package name of Oppo/Realme Camera on ColorOS 7/realmeUI 1 , ColorOS 6 & Lower.
* com.oplus.camera is package name of Oppo/Realme Camera on ColorOS 11/realmeUI 2  & ColorOS 12/realmeUI 3.
* ( oplus = merged codename of oppo + realme + oneplus blobs & packages, all Realme & Oppo Devices with RUI 2/Cos11 use oplus stuff, Oneplus with Nord 2 uses Oplus stuff too )
Change-Id: I9dbbeeec919ce133cfa8a5df53c9ffa2795ca201
Signed-off-by: techyminati <sinha.aryan03@gmail.com>
> Lawnicons: Link Oppo/realme Camera to Camera Icon

- app/src/main/res/xml/grayscale_icon_map.xml
The Firefox Nightly icon is closer matching to the stable icon so a seperate drawable isn't needed
> map Firefox Nightly to Firefox stable

- app/src/main/res/xml/grayscale_icon_map.xml
I saw the SMS on OxygenOS icon was not themed, so I figured out opening a PR could help.
> Add "com.oneplus.mms" to messages category.

- app/src/main/res/xml/grayscale_icon_map.xml
Fixes #334 
Just links Aliucord to the Discord icon.
Note: Both entries are named Discord so they won't appear as duplicates in the app. I don't know if this is the correct way to do it, but it's the way I did it.
> Link Aliucord to Discord

- app/src/main/res/xml/grayscale_icon_map.xml
Use mBank PL icon for CZ and SK versions as well.
FOSS Browser's icon is very similar existing Jelly one, as you can see in pictures below:
> mBank CZ, SK and FOSS Browser icons

- app/src/main/res/drawable/protonmail.xml
- svgs/protonmail.svg
Made the ProtonMail icon more accurate to its original version
> Refine ProtonMail icon

- app/src/main/res/xml/grayscale_icon_map.xml
- GrapheneOS Camera (Google Play) to `@drawable/camera`
- Koler to `@drawable/dialer`
- MatLog Libre and Debug to `@drawable/matlog`
> Link a few missing app icons

- app/src/main/res/xml/grayscale_icon_map.xml
This update is just to allow a GCam variant use the existing camera icon.
The package that'll be supported is:
```
com.googleCamera.Wichaya8
````
> Support GCam variant from Wichaya8

- app/src/main/res/xml/grayscale_icon_map.xml
Resolves #577
`com.asus.camera` was already in *grayscale_icon_map.xml*
> link `@drawable/dialer` to `com.asus.dialer`

- app/src/main/res/xml/grayscale_icon_map.xml
Oxygen OS 12 dialer app icon is showing as contact icon
> Oxygen OS 12 dialer app icon is showing as contact icon

- app/src/main/res/xml/grayscale_icon_map.xml
:✓:Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
* Camera (linked `org.lineageos.selfie` to `@drawable/camera`)
> link lineage os 20 camera to camera

- app/src/main/res/xml/grayscale_icon_map.xml
Links recorder icon to OnePlus Recorder
Renames OnePlus gallery app to photos
* OnePlus Gallery (renamed from `Gallery` to `Photos`)
* OnePlus Recorder (linked `com.oneplus.soundrecorder` to `@drawable/recorder`)
> Link OnePlus Recorder + rename OnePlus Gallery to Photos

- app/src/main/res/xml/grayscale_icon_map.xml
* Feeder (linked `com.nononsenseapps.feeder.play` to `@drawable/feeder`)
* Revanced Manager (linked `app.revanced.manager.flutter` to `@drawable/youtube_revanced`)
> link feeder playstore version to feeder and revanced manager to youtube revanced

- app/src/main/res/xml/grayscale_icon_map.xml
Links 2 packages to icons
* Burger King Ireland (linked `ie.whopper.android` to `@drawable/burger_king`)
* NewPipe Legacy (linked `org.schabi.newpipelegacy` to `@drawable/newpipe`)
> Link Burger King IE + NewPipe Legacy

- app/src/main/res/drawable/grapheneos_apps.xml
- app/src/main/res/drawable/grapheneos_auditor.xml
- app/src/main/res/xml/grayscale_icon_map.xml
- svgs/grapheneos_apps.svg
- svgs/grapheneos_auditor.svg
Added icons for 2 apps [GrapheneOS](https://grapheneos.org/) comes preinstalled with: [Apps](https://github.com/GrapheneOS/Apps) and [Auditor](https://github.com/GrapheneOS/Auditor).
* Apps (`app.grapheneos.apps`)
* Auditor (`app.attestation.auditor`)
> Add icons for GrapheneOS apps

- app/src/main/res/drawable/scrambled_exif.xml
- app/src/main/res/xml/grayscale_icon_map.xml
- svgs/scrambled_exif.svg
Added icon for [Scrambled Exif](https://gitlab.com/juanitobananas/scrambled-exif).
Note that the icon is purposely not centered and anchored in the top-right corner of the 160x160 content area, similar to the [original icon](https://gitlab.com/juanitobananas/scrambled-exif/-/blob/master/fastlane/standard/metadata/android/en-US/images/icon.png). If it would be better to be centered instead (or perhaps scaled down so the offset is more obvious), let me know.
* Scrambled Exif (`com.jarsilio.android.scrambledeggsif`)
> Add icon for Scrambled Exif

- app/src/main/res/xml/grayscale_icon_map.xml
* Nextcloud Dev (linked `com.nextcloud.android.beta` to `@drawable/nextcloud`)
> Link nextcloud dev to nextcloud

- app/src/main/res/xml/grayscale_icon_map.xml
* FM Radio (linked `com.android.fmradio` to `@drawable/fm_radio`)
> Link AOSP FM Radio to FM Radio

- app/src/main/res/xml/grayscale_icon_map.xml
I thought I had readded NewPipe (`org.schabi.newpipe`) I removed in PR #611 for some reason already ^^;
But yeah, readded them 👍 
* NewPipe (linked `org.schabi.newpipe` to `@drawable/newpipe`)
> Relinked NewPipe to Drawable

- app/src/main/res/drawable/asos.xml
- app/src/main/res/drawable/black_screen.xml
- app/src/main/res/drawable/oxygen_updater.xml
- app/src/main/res/drawable/roblox.xml
- app/src/main/res/drawable/stats_fm.xml
- app/src/main/res/drawable/stocard.xml
- app/src/main/res/drawable/white_border.xml
- app/src/main/res/drawable/zepp_life.xml
- app/src/main/res/xml/grayscale_icon_map.xml
- svgs/asos.svg
- svgs/black_screen.svg
- svgs/oxygen_updater.svg
- svgs/roblox.svg
- svgs/stats_fm.svg
- svgs/stocard.svg
- svgs/white_border.svg
- svgs/zepp_life.svg
All fairly simple shapes
* Stats.fm (`dev.netlob.spotistats`)
* Roblox (`com.roblox.client`)
* Black Screen (`io.japp.blackscreen`)
* Oxygen Updater (`com.arjanvlek.oxygenupdater`)
* Zepp Life (`com.xiaomi.hm.health`)
* Asos (`com.asos.app`)
* Stocard (`de.stocard.stocard`)
* White Border (`com.vector123.whiteborder`)
* Linked `weather.svg` to `net.oneplus.weather`
> Several icons added

- app/src/main/res/xml/grayscale_icon_map.xml
* DeepL (linked `com.jamal2367.deepl` to `@drawable/deepl`)
* DeepL (linked `com.example.deeplviewer` to `@drawable/deepl`)
* Threema (linked `ch.threema.app.hws` to `@drawable/threema`)
* Threema (linked `ch.threema.app.fdroid` to `@drawable/threema`)
> Link deepl and threema apps

- app/src/main/res/xml/grayscale_icon_map.xml
* App Name (linked `org.lineageos.aperture` to `@drawable/camera`)
> Link org.lineageos.aperture to camera

- app/src/main/res/xml/grayscale_icon_map.xml
Add Icon for [Etar](https://f-droid.org/en/packages/ws.xsoh.etar/): `<icon** drawable="@drawable/calendar" package="ws.xsoh.etar" name="Calendar" />`
* App Name (linked `@drawable/calendar` to `ws.xsoh.etar`)
> Add Etar Calender

- app/src/main/res/xml/grayscale_icon_map.xml
Linked YT Music to YT Music Revanced package
Linked YT Music's icon to YT Music Revanced
* YT Music (linked `app.android.apps.youtube.music` to `@drawable/app.revanced.android.apps.youtube.music)
> Linked YT Music icon to Revanced version

- app/src/main/res/xml/grayscale_icon_map.xml
Added a link to the motorola recorder app.
❌ Bug fix (non-breaking change which fixes an issue)
❌ General change (non-breaking change that doesn't fit the above categories like copyediting)
* App Name (linked `com.motorola.audiorecorder` to `@drawable/recorder`)
> Added links for motorola recorder app

- app/src/main/res/xml/grayscale_icon_map.xml
Link calendar icon to lineageos calendar
:white_check_mark: : Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
linked
* Calendar (linked `org.lineageos.etar` to `@drawable/calendar`)
> Link calendar icon to lineageos calendar

- app/src/main/res/xml/grayscale_icon_map.xml
- Linked com.oneplus.note to drawable/notes
- Linked com.devgary.ready to drawable/reddit
:heavy_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
* App Name (linked `com.oneplus.note` to `@drawable/notes`)
* App Name (linked `com.devgary.ready` to `@drawable/reddit`)
> Link Oneplus Note app, Ready app

- app/src/main/res/xml/grayscale_icon_map.xml
* Nextcloud Cookbook (linked `de.micmun.android.nextcloudcookbook` to `@drawable/cookbook`)
> Link another Nextcloud Cookbook

- app/src/main/res/xml/grayscale_icon_map.xml
Link another neo-store and neo-backup
* App Name (linked `com.machiav3lli.fdroid.neo` to `@drawable/neo_store`)
* App Name (linked `com.machiav3lli.backup.neo` to `@drawable/neo_backup`)
> Link Neo Backup, Neo Store

- app/src/main/res/xml/grayscale_icon_map.xml
SVG and drawable xml are preset but no entry in grayscale.xml
> Add notesnook

- build.gradle.kts
See https://github.com/LawnchairLauncher/lawnicons/pull/815#discussion_r1020803580
> Revert "Bump com.sergei-lapin.napt from 1.17 to 1.18"

- app/src/main/res/xml/grayscale_icon_map.xml
https://github.com/Darkempire78/OpenCalc
* OpenCalc (linked `com.darkempire78.opencalculator` to `@drawable/calculator`)
> Link OpenCalc to calculator

- app/src/main/res/xml/grayscale_icon_map.xml
* UntrackMe (linked `app.fedilab.nitterizeme` to `@drawable/trust_wallet`)
* TimeTable - a FOSS timetable app, icon looks very similar to the news glyph, even though the app has a different purpose (linked `com.asdoi.timetable` to `@drawable/news`)
* Librera Reader - not related to google, but icon looks very similar to google books glyph (linked `com.foobnix.pro.pdf.reader` to `@drawable/google_play_books`)
* Iconify - a FOSS UI customization app, again, totally unrelated to the original glyph but looks very similar (linked `com.drdisagree.iconify` …
> Link 4 icons

- app/src/main/res/drawable/adidas.xml
- app/src/main/res/drawable/geometry_dash.xml
- app/src/main/res/drawable/kicker.xml
- app/src/main/res/drawable/mullvad_vpn.xml
- app/src/main/res/xml/grayscale_icon_map.xml
- svgs/adidas.svg
- svgs/geometry_dash.svg
- svgs/kicker.svg
- svgs/mullvad_vpn.svg
I made icons for:
* [kicker](https://play.google.com/store/apps/details?id=com.netbiscuits.kicker&hl=en_GB&gl=US)
* [Geometry Dash](https://play.google.com/store/apps/details?id=com.robtopx.geometryjump&hl=en_GB&gl=US)
* [adidas](https://play.google.com/store/apps/details?id=com.adidas.app&hl=en_GB&gl=US)
and fixed a small error I noticed on the Mullvad VPN icon:
:white_check_mark:  Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
* kicker (`com.netbiscuits.kicker`)
* Geometry Dash (`com.robtopx.geometryjump`)
* adidas (`com.adidas.app`)
* Mullvad VPN (`net.mullvad.mullvadvpn`)
> Add 3 icons & fix Mullvad VPN icon

- app/src/main/res/xml/grayscale_icon_map.xml
✅  Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
* ViMusic (linked `it.vfsfitvnm.vimusic` to `@drawable/mi_music`)
> Add icon link for ViMusic

- app/src/main/res/drawable/bandcamp.xml
- app/src/main/res/xml/grayscale_icon_map.xml
- svgs/bandcamp.svg
Adding icon for music app bandcamp.
* App Name (`com.bandcamp.android`)
* App Name (linked `com.bandcamp.android` to `@drawable/bandcamp`)
> Add icon for Bandcamp

- app/src/main/res/xml/grayscale_icon_map.xml
Link another vodafone app
* App Name (linked `com.vodafone.selfservis` to `@drawable/meinvodafone`)
> Add another vodafone link

- app/src/main/kotlin/app/lawnchair/lawnicons/model/IconInfo.kt
- app/src/main/kotlin/app/lawnchair/lawnicons/ui/component/ClickableIcon.kt
- app/src/main/kotlin/app/lawnchair/lawnicons/ui/component/IconInfoPopup.kt
- app/src/main/kotlin/app/lawnchair/lawnicons/ui/component/IconPreview.kt
- app/src/main/kotlin/app/lawnchair/lawnicons/ui/component/IconPreviewGrid.kt
- app/src/main/kotlin/app/lawnchair/lawnicons/ui/util/StringConstants.kt
- app/src/main/kotlin/app/lawnchair/lawnicons/util/GetIconInfo.kt
- app/src/main/res/values/strings.xml
Added the ability to view information about the icon when clicking on it
Fixes #787
> Support view icon info when tapping an icon

- app/src/main/res/xml/grayscale_icon_map.xml
Linked icons for QR Scanner (https://github.com/SecUSo/privacy-friendly-qr-scanner)
Session Fdroid (https://f-droid.org/ru/packages/network.loki.messenger.fdroid)
Fork Client (https://github.com/Forkgram/TelegramAndroid)
* QR Scanner (linked `com.secuso.privacyFriendlyCodeScanner` to `@drawable/qr_reader`)
* Session Fdroid (linked `network.loki.messenger.fdroid` to `@drawable/session`)
* Fork Client (linked `org.forkclient.messenger.beta` to `@drawable/telegram`)
> Add icon link for QR Scanner, Session Fdroid, Fork Client

- app/src/main/res/drawable/klarna.xml
- app/src/main/res/xml/grayscale_icon_map.xml
- svgs/klarna.svg
Adding icon for the Klarna app. I am not sure about the dot; I made it to have a diameter of 12.
https://play.google.com/store/apps/details?id=com.myklarnamobile
* App Name (`com.myklarnamobile`)
* App Name (linked `com.myklarnamobile` to `@drawable/klarna`)
> Add icon for Klarna

- app/src/main/res/xml/grayscale_icon_map.xml
Just clean-installed a custom ROM and found out that the current Files Shortcut app that I previously used didn't link to the proper stock file manager app that I prefer, so I installed another one, and thought of theming it with the already existing drawable ^^
https://play.google.com/store/apps/details?id=com.marc.files
* Files (linked `com.marc.files` to `@drawable/files`)
> Link Marc's Files

- settings.gradle.kts
- svgprocessor/build.gradle.kts
- svgprocessor/src/main/kotlin/app/lawnchair/lawnicons/helper/Application.kt
- svgprocessor/src/main/kotlin/app/lawnchair/lawnicons/helper/ConfigProcessor.kt
- svgprocessor/src/main/kotlin/app/lawnchair/lawnicons/helper/SvgFilesProcessor.kt
- svgprocessor/src/main/kotlin/app/lawnchair/lawnicons/helper/XmlUtil.kt
Introduce automation to reduce some maintance work.
- Since lawncions will act as icon pack, we need to add components details to appfilter.xml , drawabale.xml and grayscale_icon_map.xml . Even now developers are creating svg files and vector assests.
- Idea is to let developer create svg file and appfilter.xml file alone and helper script to create others file during build.
Related pr : https://github.com/LawnchairLauncher/lawnicons/pull/815
> Add svgprocessor module

- app/src/main/res/xml/grayscale_icon_map.xml
https://apt.izzysoft.de/fdroid/index/apk/com.example.retouchephoto
* Litrato (linked `com.example.retouchephoto` to `@drawable/photo_editor`)
> Add Litrato photo editor

- app/src/main/res/xml/grayscale_icon_map.xml
https://www.celsoazevedo.com/files/android/google-camera/dev-greatness/f/dl6/
* App Name (linked `com.google.android.GoogleCamera.cameralite` to `@drawable/camera`)
> Link Greatness's GCam mod to camera

- app/src/main/res/drawable/teufel.xml
- app/src/main/res/xml/grayscale_icon_map.xml
- svgs/teufel.svg
Added the teufel logo for a couple of apps. The apps themselves always have the same logo, but in different colors. This does not apply to this icon pack so I linked all of them :)
* App Name (`com.raumfeld.android.controller`)
* App Name (linked `com.raumfeld.android.controller` to `@drawable/teufel`)
* App Name (linked `com.teufel.SmartAudio` to `@drawable/teufel`)
* App Name (linked `com.wifiaudio.Teufel` to `@drawable/teufel`)
* App Name (linked `de.teufel.android.app.bluetooth.playstore` to `@drawable/teufel`)
> Add icon for Teufel apps

- app/src/main/res/xml/grayscale_icon_map.xml
This package name is of the clone package (which can be installed alongside original)
https://thedise.me/instander
Added a link to instagram icon for instander package
* Instander (linked `com.instander.android` to `@drawable/instagram`)
> Link Instander to Instagram

- app/src/main/res/xml/grayscale_icon_map.xml
[Vanadium](https://vanadium.app) is a hardened fork of Chromium for the GrapheneOS project. It shares the same icon style as the base projects (Chromium, Chrome), so it should be linked that way.
* Vanadium (linked `app.vanadium.browser` to `@drawable/google_chrome`)
> Link Vanadium to Chrome

- app/src/main/res/xml/grayscale_icon_map.xml
* Magisk Delta (linked `io.github.huskydg.magisk` to `@drawable/magisk`)
> Link Magisk Delta to Magisk

- build.gradle.kts
https://developers.google.com/android/guides/releases#december_05_2022
Link https://github.com/LawnchairLauncher/lawnchair/pull/3217.
> Bump oss-licenses-plugin to 0.10.6

- app/src/main/res/xml/grayscale_icon_map.xml
https://f-droid.org/en/packages/com.termux.styling
https://f-droid.org/en/packages/com.termux.window
https://f-droid.org/en/packages/com.termux.widget
https://f-droid.org/en/packages/com.termux.api
https://f-droid.org/en/packages/com.termux.boot
https://f-droid.org/en/packages/com.termux.tasker
✅  Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
* Termux Styling (linked `com.termux.styling` to `@drawable/termux`)
* Termux Float (linked `com.termux.window` to `@drawable/termux`)
* Termux Widget (linked `com.termux.widget` to `@drawable/termux`)
* Termux Api (linked `com.termux.api` to `@drawable/termux`)
* Termux Boot …
> Link all termux apps to termux

- app/assets/appfilter.xml
This pull adds another `<item>` in the app/assets/appfilter.xml file, which adds the app `deckers.thibault.aves.libre`. It is the offical libre counterpart of `deckers.thibault.aves` made for F-Droid. It's drawable still links to `aves_gallery`, the one that its non-free counterpart (`deckers.thibault.aves` on Gplay) uses in lawnicons, because they are meant to be identical except the presence of non-free deps.
Fixes #994 
:x: Bug fix
:white_check_mark: Icon addition
:x: General change
* App Name (linked `deckers.thibault.aves.libre` to `@drawable/aves_gallery`)
> Link Aves gallery's icon to its libre counterpart of F-Droid

- app/assets/appfilter.xml
Apparently, the link for Megalodon to its own icon was lost while merging. I relinked it. If this was intentional, it might make sense to specify in CONTRIBUTING how to handle icons of forks that have their own logos.
* App Name (linked `de.mm20.launcher2.nightly` to `@drawable/kvaesitso`)
* App Name (linked `de.mm20.launcher2.debug` to `@drawable/kvaesitso`)
* App Name (linked `org.joinmastodon.android.sk` to `@drawable/megalodon`)
> Add links for Kvaesitso dev versions & relink Megalodon

- app/assets/appfilter.xml
That's the same icon as AccuBattery, i don't know if that's the right way to do it or i should copy the svg
Added AccA
* AccA (linked `mattecarra.accapp` to `@drawable/accubattery`)
> Add icon to AccA

- app/assets/appfilter.xml
Somehow the links for Qobuz and Duolingo got messed up. (Duolingo probably because of my **SICK** streak 😎 )
I added the two activities as shown in the IconRequest app. Not sure if the links still remaining (especially Qobuz) are valid?
> Add links for Duolingo & Qobuz

- app/assets/appfilter.xml
- svgs/auxio.svg
- svgs/polaris.svg
- svgs/vimusic.svg
This pull adds 2 new icons, namely:
1. [Polaris Android](https://play.google.com/store/apps/details?id=agersant.polaris) - official android client for the [Polaris music streaming server](https://github.com/agersant/polaris).
2. [ViMusic](https://f-droid.org/packages/it.vfsfitvnm.vimusic/) - an open source app to stream music from YouTube Music.
and updates 1, i.e., [Auxio](https://f-droid.org/app/org.oxycblt.auxio) to resemble it's [current icon](https://github.com/OxygenCobalt/Auxio/blob/dev/fastlane/metadata/android/en-US/images/icon.png) and [switch to an outlined design](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md#icon-guidelines).
:x: Bug fix
:white_check_mark: Icon addition
:x: General change
* Polaris (`agersant.polaris`)
* ViMusic …
> Add 2 icons and update 1

- app/assets/appfilter.xml
Added link for wattz (it was there before but I'm not sure how it got removed so i re-added it)
* Wattz (linked `dubrowgn.wattz/dubrowgn.wattz.MainActivity` to `@drawable/wattz`)
> Add link for wattz

- find_missing.py
I added the find_missing.py tool, it is similar to the find_duplicates.py
When you run the tool (`python3 find_missing.py`) it prints list of icons that are in the svg directory but are not present in the appfilter.xml file (unlinked/unused icons)
the current output is:
```
securego_plus.svg
flashy.svg
movie_lab.svg
show_youtube_dislikes.svg
samsung_health_monitor.svg
animiru.svg
gramotnee.svg
mi_freeform.svg
russian_language_quiz.svg
calendar.svg
pixapencil.svg
tricount.svg
tinkoff_work.svg
camera_date_folders.svg
penta.svg
coinvero.svg
schulmanager.svg
z1.svg
russian_language.svg
nc_photos.svg
erste_hilfe.svg
xvii.svg
prognoza.svg
revanced_extended.svg
``` …
> Add find_missing.py

- app/assets/appfilter.xml
Linked Telegraph (Telegram mod) to Telegram icon
* Telegraph (linked `ir.ilmili.telegraph` to `@drawable/telegram`)
> Link Telegraph to Telegram icon

- app/assets/appfilter.xml
Link `com.android.email` to samsung_email icon. It has the same icon on ColorOS
* Mail (linked `com.android.email` to `@drawable/samsung_email`)
> Link `com.android.email` to samsung_email icon

- gradle/wrapper/gradle-wrapper.properties
Allows for verification for the downloaded binary using SHA-256 hash comparison. This increases security against targeted attacks by preventing a man-in-the-middle attacker from tampering with the downloaded Gradle and in rare case, attacker gets access to the Gradle servers.
Renovate should be able to bump the Gradle version and checksums.
> **Note**: SHA-256 hash come from https://gradle.org/release-checksums/
> Add SHA-256 verification to Gradle

- app/assets/appfilter.xml
The F-Droid version of Fox's Magisk Module Manager has a different package id.
* Fox's Magisk Module Manager (linked `com.fox2code.mmm.fdroid` to `@drawable/fox_mmm`)
> Link icon for F-Droid version of Fox's MMM

- icontool.py
Added fix for `icontool.py` not being able to parse package name or activity name with underscore and it leaving full path instead of basename for svg drawable name for add icon action.
Fixes #1216 and #1217 
> Icontool fix for underscore in packagename and drawable name for adding icons

- app/build.gradle.kts
- app/proguard-rules.pro
Fix crash in release:
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/animation/AnimatedContentScope;
at q1.i.Z(Unknown Source:0)
at i.n.a(Unknown Source:676)
at q1.q.a(Unknown Source:476)
at q1.c.a(Unknown Source:80)
at q1.c.M(Unknown Source:28)
at A.K0.g(Unknown Source:14)
at A.H.s0(Unknown Source:188)
at A.H.I(Unknown Source:219)
at A.H.q0(Unknown Source:32)
at A.N.B(Unknown Source:18)
at A.T0.E(Unknown Source:70)
at A.R0.Z(Unknown Source:370)
at androidx.compose.ui.platform.e0.doFrame(Unknown Source:6)
at androidx.compose.ui.platform.d0.X(Unknown Source:33)
at androidx.compose.ui.platform.c0.doFrame(Unknown Source:12)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java: …
```
> Downgrade material-motion-compose-core to 0.11.3

- app/assets/appfilter.xml
From issue #1252
Fixes #1252 
:white_check_mark:  Bug fix (non-breaking change which fixes an issue)
* App Name (linked `com.mcdonalds.gma.cn` to `mcdonalds`)
> Fix McDonald's link

- .github/README.md
Users will be able to download debug APKs from [nightly.link](https://nightly.link/) instead of Github actions which will eliminate the need to have an account. The nightly link is automatically updated.
Fixes #1251 
✅ : General change (non-breaking change that doesn't fit the above categories, such as copyediting)
> Add nightly.link to download debug apks without GH account

- .gitignore
- app/assets/appfilter.xml
* Link BiliComic to bilibili icon
* Link 5 OEM Apps' icons
[commit 1] Linked BiliComic to bilibili icon, and added IDEs cache directory to /.gitignore.
[commit 2] Linked 5 OEM Apps' icons.
* App Name (linked `com.bilibili.comic` to `@drawable/bilibili`)
* App Name (linked `com.motorola.cn.calendar` to `@drawable/calendar`)
* App Name (linked `com.asus.deskclock` to `@drawable/clock`)
* App Name (linked `com.motorola.cn.gallery` to `@drawable/gallery`)
* App Name (linked `com.motorola.stylus` to `@drawable/notes`)
* App Name (linked …
> Linked 6 apps' icons

- app/build.gradle.kts
Fix build error from https://github.com/LawnchairLauncher/lawnicons/actions/runs/5262850812/jobs/9512426343
```
A problem was found with the configuration of task ':app:lintVitalAnalyzeAppRelease' (type 'AndroidLintAnalysisTask').
- Gradle detected a problem with the following location: '/home/runner/work/lawnicons/lawnicons/app/build/generated/dependencyAssets'.
Reason: Task ':app:lintVitalAnalyzeAppRelease' uses this output of task ':app:copyAppReleaseArtifactList' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
Possible solutions:
1. Declare task ':app:copyAppReleaseArtifactList' as an input of ':app:lintVitalAnalyzeAppRelease'.
2. Declare an explicit dependency on …
```
> Let lintVitalAnalyzeAppRelease depend on copyAppReleaseArtifactList

- app/assets/appfilter.xml
Linked [Showly icon](https://github.com/LawnchairLauncher/lawnicons/blob/develop/svgs/showly.svg) to [Showly OSS](https://github.com/1RandomDev/showly-oss)
* Showly OSS (linked `com.michaldrabik.showly_oss` to `@drawable/showly`)
> Link Showly icon to showly-oss

- .github/workflows/first_pr_interaction.yml
Right now the action sometimes errors, this should make it not error
> Fix first-interaction workflow

- .github/PULL_REQUEST_TEMPLATE/icon_addition.md
Previously the checklist in the pr template used `[x] ...`
:white_check_mark:  General change (non-breaking change that doesn't fit the above categories, such as copyediting)
> fix checklist rendering in pr template

- app/assets/appfilter.xml
`hayalla` reported a new activity is being used for Discord.
this PR adds `com.discord/com.discord.main.MainDefault` to use the Discord icon.
> new Discord activity

- app/assets/appfilter.xml
The icon for AL-Chan wasn't getting applied because the activity name the app was using was different from the one lawnicons was using. I fixed that.
> Updated AL-Chan activity name

- icontool.py
Corrects spelling error in the variable name for reading calendar components. 
It changes this variable from `readd_calendar_components` to `read_calendar_components`.
✅ General change (non-breaking change that doesn't fit the above categories, such as copyediting)
> Correct typo

- app/assets/appfilter.xml
From IconRequest:
```
<item component="ComponentInfo{dev.beefers.vendetta/com.discord.main.MainDefault}" drawable="discord"/>
<item component="ComponentInfo{com.google.android.inputmethod.latin/com.google.android.libraries.inputmethod.launcher.LauncherActivity}" drawable="gboard"/>
```
* Gboard (`com.google.android.inputmethod.latin`)
* Vendetta (`dev.beefers.vendetta`)
> Update Gboard and Vendetta to the latest activity

- app/assets/appfilter.xml
My McDonalds App was not linked with the available icon:
- McDonald's Canada
- https://play.google.com/store/apps/details?id=com.mcdonalds.superapp&hl=en_US
* McDonald's (linked `com.mcdonalds.superapp` to `@drawable/mcdonalds`)
> Link McDonald's package

- app/assets/appfilter.xml
* Camera (linked `com.samsung.agc.gcam91`, `com.agc.gcam91` to `@drawable/camera`)
* Camera (linked `com.samsung.agc.gcam90`, `com.agc.gcam90` to `@drawable/camera`)
* Camera (linked `com.samsung.agc.gcam88`, `com.agc.gcam88` to `@drawable/camera`)
* Camera (linked `com.google.android.GoogleCameraLMC88` to `@drawable/camera)
* _you guessed it_ Camera (linked `com.android.MGC_9_1_098` to `@drawable/camera`)
> Link multiples gcam mod 8.8 and 9.x

- .github/PULL_REQUEST_TEMPLATE/icon_addition.md
Discovered another link that broke after moving docs.
> Updating the link to Lawnicons guidelines

- app/build.gradle.kts
We should avoid using internal tasks in 49b5567769064b49a6337e4b4b9913c94f6e46cf.
Refs https://github.com/android/gradle-recipes/blob/1cd59c8951b59fd692f5194bfd451db2473975b9/addCustomAsset/build-logic/plugins/src/main/kotlin/CustomPlugin.kt#L63-L70.
> Optimize artifacts copy task

- app/assets/appfilter.xml
Fulfilling requests.
Mercado Pago (`com.mercadopago.wallet/com.mercadopago.wallet.splashscreen.SplashScreenActivity`)
Meta Quest (`com.oculus.twilight/com.oculus.twilight.crossapp.activity.XOCLoginActivity`)
Nagram (`xyz.nextalone.nagram/org.telegram.messenger.PremiumIcon`)
Neon (`br.com.neon/br.com.neon.features.login.ui.activities.HomeOnboardingActivity`)
PhotoScan (`com.google.android.apps.photos.scanner/com.google.android.apps.photos.scanner.home.HomeActivity`)
Poweramp Equalizer (`com.maxmpz.equalizer/com.maxmpz.equalizer.rounded_mu`)
Retouch Advasoft (`com.advasoft.touchretouch/com.advasoft.touchretouch4.LicenseActivity`)
Smash Hit (`com.mediocre.smashhit/com.mediocre.smashhit.MainActivity`)
Tasker (`net.dinglisch.android.taskerm/com.joaomgcd.taskerm.util.ActivitySecondaryApp`)
> +9 links: Meta Quest, Nagram, Retouch Advasoft

- app/assets/appfilter.xml
Linked the RootlessJamesDSP icon to become the JamesDSP icon.
* App Name (linked `james.dsp/me.timschneeberger.rootlessjamesdsp.activity.MainActivity` to `@drawable/rootless_james_dsp`)
* App Name (linked `james.dsp/james.dsp.activity.DSPManager` to `@drawable/rootless_james_dsp`)
> Link RootlessJamesDSP icon to JamesDSP

- .github/ISSUE_TEMPLATE/general_discussion.yml
- .github/PULL_REQUEST_TEMPLATE/icon_addition.md
- .github/pull_request_template.md
I suggest some changes to the templates to remove unnecessary information and clarify what is needed from the contributor.
- Removed [DISCUSSION] from the issue template because it was duplicating the label.
- Shortened the subheadings in the icon addition template because they were duplicating the header.
- Removed the note about the icon being added from the request form, because that wasn't used and you can see in the current requests table what requests are fulfilled.
- Removed the indentation in the icon lists to make it easier to read.
- Renamed the package name example to make it closer to the real ones.
- …
> Updating and simplifying templates

- CONTRIBUTING.md
Since we have issues with naming, and out of a desire to simplify the search for different languages, I propose to describe the rules for naming apps and drawables. I suggest we stick to them.
If any wording is questionable, let's take that into consideration. I also used `~~` as a name separator, because `/` and `|` are sometimes found in app names, and `~` is sometimes found in Japanese part of Google Play. Any of these characters written twice would probably work, but tildes are neater in my opinion.
Fixes #1715
> Naming guidelines

- CONTRIBUTING.md
It happens that only English letters are used in the name of the app, although the app may be, say, Turkish. Often there is no point in translating such a name, as it's convenient to search for it by its original name.
At the same time, if the name contains characters from other languages, it can make the search more difficult for people who don't have a suitable keyboard layout.
Clarified what to do about such cases.
:white_check_mark:  General change (non-breaking change that doesn't fit the above categories, such as copyediting)
> Clarified how to name apps w/o a name localization

- .github/PULL_REQUEST_TEMPLATE/general_change.md
- .github/PULL_REQUEST_TEMPLATE/icon_addition.md
- .github/pull_request_template.md
I suggest leaving one checkbox. The main purpose of this list is to remind contributors about the Lawnicons Guidelines and what to expect next. It doesn't work, because judging by the reviews, many people put checkboxes just for fun. It's a mockery that checkboxes should be placed by keyboard, but I see the benefit of this section, it's better to keep it. So I minimize unnecessary actions.
**Changelog**
- three checkboxes became one.
- marked when the last guidelines update was, so old contributors would be aware.
- changed the wording about builds because it is inconvenient to first make a PR, then make sure that Lawnicons builds correctly, and then check that checkbox. Many contributors checked the checkbox first and then saw the result of the build. New contributors waited for approval …
> Simplifying Contributor's checklist and instructions updates

- CONTRIBUTING.md
I have clarified the process for requesting icons to make it clearer which copy option is suitable for filling out the form.
> Clarified the process of filling out the icon request form

- CONTRIBUTING.md
The previous wording led to errors with icon sizes a couple times, so I added a clarification to TL;DR.
> Clarified the size of icons in the TL;DR section

- app/assets/appfilter.xml
Nykaa, Nykaa Fashion, Nykaa Man themed icons were not applied due to wrong activity names in `appfilter.xml`
> Updated some icon app activity names 

- app/assets/appfilter.xml
Aliucord Manager is the upcoming replacement app for Aliucord Installer, which retains the same logo/app icon
> Link Aliucord Manager to Aliucord Installer

- CONTRIBUTING.md
In cases where the semantic part of an app name is written in English letters, transliteration does not make sense and will only take up space.
> Softened the point about transliteration of names

- README.md
Considering the experience since the last change in the description, I decided to make it more concise and informative.
- removed the mention of icontool.py since few people need it, given the average size of PRs and in this form, it seems to people that this is some kind of software with UI (not a command line);
- removed the line about contribution code section, because it says about the code in the first sentence, there are no new devs, and it's easy to jump from the guidelines to the contributing code section;
- added a link to Lawnchair Discord so that people have a direct opportunity to clarify how to do something …
> Added Discord to the description and removed unnecessary info

- app/assets/appfilter.xml
Apparently, there is a new apk id for OrganicMaps when installed from Github.
> Link app.organicmaps.web

- app/assets/appfilter.xml
Added links for Decathlon, MicroG Settings and n11. Fixed Glimpse link that I've made a mistake in my recent pull request.
Decathlon (`com.decathlon.app` → `decathlon.svg`)
MicroG Settings (`app.revanced.android.gms` → `microg_settings`)
n11 (`com.dmall.mfandroid` → `n11`)
Gallery (`org.lineageos.glimpse`)
> Add 3 links, fix 1

- CONTRIBUTING.md
> Fixed the guidelines link in the adding an icon section

- CONTRIBUTING.md
I clarified the transliteration guidelines so that it would become clearer when it should be done. This eliminates the addition of far-fetched and actually useless transliterations.
> Clarified the guidelines for transliteration of names

- app/assets/appfilter.xml
https://github.com/material-components/material-components-android
M3 Catalog (`io.material.catalog/io.material.catalog.main.MainActivity` → `material_catalog.svg`)
> Link official M3 Catalog

- app/src/main/kotlin/app/lawnchair/lawnicons/ui/destination/About.kt
- app/src/main/kotlin/app/lawnchair/lawnicons/ui/destination/Acknowledgements.kt
- app/src/main/kotlin/app/lawnchair/lawnicons/ui/destination/Contributors.kt
Fixes incorrect list padding cutting off content in the About, Contributors, and Acknowledgement screens.
<details>
<summary>Screenshots</summary>
Before
After
Before
After
Before
After
</details>
> Fix list padding in About, Contributors, and Acknowledgement screens

- docs/icontool_guide.md
At the moment, 4 contributors have encountered errors when sorting through icontool.py, as a result, they needed to fix appfilter.xml to remove duplicates or pass the style check.
I added a warning about the current state of the command so that people avoid unnecessary work.
> Added a warning about using the sort command in icontool.py

- README.md
- added a line for devs to highlight the tasks for their skills.
- slightly changed the first part of the description to shorten it without losing its meaning.
- mentioned Lawnchair 14 Beta 2 to highlight the new version. I have not removed the mention of the old one, because the new version works unstable when configuring icons on some systems.
- "Some launchers may also support Lawnicons for themed icons." — deleted because the previous sentence implies support for themed icons.
> Optimized the wording in the description and added an invitation for devs

- README.md
> Moved the phrase about self-fulfilling a request from the Contributing to the Requesting icons

- CONTRIBUTING.md
It is impossible to start the name of the drawable with a digit and this is not obvious, as a result, contributors periodically correct the name after creating a PR. It is better to start the name of the drawable with the allowed symbol in order to reduce the likelihood of error and give contributors a simple solution to the issue. 
[Artcicons](https://github.com/Arcticons-Team/Arcticons) — thanks for the idea.
> How to name drawables if the app name starts with a digit

- .github/workflows/icon_checklist.yml
The icon checklist workflow [failed to run](https://github.com/LawnchairLauncher/lawnicons/actions/runs/9078779642/) on PR #2093 with error `Error: Unhandled error: HttpError: Resource not accessible by integration`, this seems to be a problem with the permissions, which is weird because it was running fine on my personal repo. Maybe there are restrictions set up on the Lawnicons repo?
I have specifically added in the permission to write a comment, so this may fix the problem. 
✅ Bug fix (non-breaking change which fixes an issue)
> Try to fix icon checklist workflow

- CONTRIBUTING.md
- README.md
Since the easiest way to request icons has changed, I'm updating the instructions.
I also delete the text that turned out to be useless and update the wording a little.
> Updating the instructions for requesting icons

- CONTRIBUTING.md
I added links to graphic editors and slightly changed the wording to make it easier for beginners to choose an icon editor.
> Added links to graphic editors

- app/build.gradle.kts
- app/src/main/res/values/themes.xml
We don't need it in a pure Compose app.
```diff
OLD: before.apk (signature: V2)
NEW: after.apk (signature: V2)
│            compressed            │           uncompressed           
├──────────┬──────────┬────────────┼──────────┬──────────┬────────────
APK      │ old      │ new      │ diff       │ old      │ new      │ diff       
──────────┼──────────┼──────────┼────────────┼──────────┼──────────┼────────────
dex │  1.4 MiB │  1.4 MiB │  -89.6 KiB │  2.9 MiB │  2.8 MiB │ -174.1 KiB 
arsc │    2 MiB │  1.5 MiB │ -479.5 KiB │    2 MiB │  1.5 MiB │ -479.5 KiB 
manifest │  3.2 KiB │  3.2 KiB │       -1 B │ 14.3 KiB │ 14.3 KiB │        0 B 
res │  7.6 MiB │  7.4 MiB │ -156.1 KiB │ 17.4 MiB │ 17.2 MiB │   -191 KiB 
native │ 96.3 KiB │ 84.2 KiB │  -12.1 KiB │ 36.5 KiB │ 36.5 KiB │        0 B …
```
> Get rid of AppCompat

- CONTRIBUTING.md
> Fixed the link to the visual balance section

- .github/ISSUE_TEMPLATE/icon_rebrand.yml
I deleted unnecessary info, clarified the terms and expanded the template a little. This way, we could see what needs to be changed, as well as catch activities that have been assigned to the wrong icons.
Most likely the preview is not quite accurate in the order of the blocks.
> Clarifying the icon update template

- .github/icon_checklist.md
I want to try to simplify the review process for reviewers and use the checklist in it.
> Updating the self-review checklist

- .github/icon_checklist.md
I added the opacity requirement and clarified who the checkboxes are useful for.
> Updating the self-review checklist 2

- .github/ISSUE_TEMPLATE/config.yml
Although most of the new links are available in the icon request table, sometimes people want to speed up the process. I suggest making a link to the instructions for them.
> New issue: Add a link to an existing icon

- .github/ISSUE_TEMPLATE/config.yml
I have clarified the description of the issue to emphasize in which cases it makes sense to link an app to an existing icon.
> Update for the app linking issue

- app/assets/appfilter.xml
- svgs/nothing_gallery.svg
Nothing Gallery (`com.nothing.gallery`)
Game Space (`com.neoteric.gamespace` → `game_space.svg`)
Dolby Manager (`co.aospa.dolby` → `dolby.svg`)
> +1 icon, + 2 links

- app/assets/appfilter.xml
Rumble and Google Gemini changed their activity names. Now they don't display correct icon with Lawnicon. Gemini reuses an older activity `RobinEntryPointActivity`. That is set to display Google logo. And rumble changed theirs to `RumbleMainActivity`. So, it displays default icon. This pr relinks them.
✅  Bug fix (non-breaking change which fixes an issue)
✅ General change (non-breaking change that doesn't fit the above categories, such as copyediting)
> Relink Gemini and Rumble

- app/assets/appfilter.xml
Link the new version of Iconify (FOSS) to the corresponding icon
Iconify (`com.drdisagree.iconify.foss` → `iconify.svg`)
> Link Iconify FOSS to Iconify icon

- .github/ISSUE_TEMPLATE/icon_rebrand.yml
- README.md
I synchronized the link from the repo description with the name of the issue type, and also created the opportunity for people to notice a pinned issue with known outdated icons.
> Copyediting for issues

- .github/release.yml
- .github/workflows/build_debug_apk.yml
I'm researching how to leave only the changelog link in the Lawnicons Nightly release.
> Trying to get the changelog link back to the Lawnicons Nightly release

- CONTRIBUTING.md
Linked sections "Adding icons and missing app components to Lawnicons" and "How to find app components" more explicitly.
> Minor copyediting to improve the guides clarity

- app/assets/appfilter.xml
中国移动浙江 ~~ China Mobile Zhejiang (`com.example.businesshall` → `china_mobile.svg`)  
> Yes, they really used this as package name... [See in Xiaomi Store](https://app.mi.com/details?id=com.example.businesshall)
> Add link for China Mobile Zhejiang

- app/src/main/kotlin/app/lawnchair/lawnicons/ui/util/ExternalLink.kt
```
> Task :app:compileAppDebugKotlin
w: file:///home/runner/work/lawnicons/lawnicons/app/src/main/kotlin/app/lawnchair/lawnicons/ui/util/ExternalLink.kt:6:5 This annotation is currently applied to the value parameter only, but in the future it will also be applied to field.
- To opt in to applying to both value parameter and field, add '-Xannotation-default-target=param-property' to your compiler arguments.
- To keep applying to the value parameter only, use the '@param:' annotation target.
See https://youtrack.jetbrains.com/issue/KT-73255 for more details.
```
> Fix the warning for use-site for @DrawableRes

- app/assets/appfilter.xml
Description included below alongside relevant components.
[wchen342](https://github.com/wchen342/ungoogled-chromium-android)'s build of Ungoogled Chromium:
- Ungoogled Chromium (`org.ungoogled.chromium` → `google_chrome.svg`)  
The short-lived Ungoogled Chromium variant with support for extensions:
- Ungoogled Chromium Extensions ([by wchen342](https://github.com/wchen342/ungoogled-chromium-android/releases?q=Extensions)) (`org.ungoogled.chromium.extensions` → `google_chrome.svg`)  
- Ungoogled Chromium Extensions ([by ungoogled-software](https://github.com/ungoogled-software/ungoogled-chromium-android/releases?q=Extensions)) (`org.ungoogled.chromium.extensions.stable` → `google_chrome.svg`)  
From the [ViTune](https://github.com/25huizengek1/ViTune/) creator's …
> +5 links, 1 changed link

- app/src/main/kotlin/app/lawnchair/lawnicons/repository/IconRepository.kt
This PR attempts to resolve #2691, by removing the `.associateBy {}` logic.
TODO: do proper testing to see if this actually resolves this PR
> fix: Fix icon list ignoring some unthemed icons

- CONTRIBUTING.md
Additional examples don't really help, but they seem to prevent people from reading the guidelines to the end. That's why I removed them.
> Shortened naming guidelines

- .github/PULL_REQUEST_TEMPLATE/icon_addition.md
I would suggest removing the description heading from the icon addition PR template because as it does not seem to serve any purpose. It is usually used to put text that is just repeating what is in the title, or just ignored and not used at all. If people need to add extra information to the PR they can do so themselves easily.
> Remove description from icon addition PR template
