- app/src/main/res/xml/grayscale_icon_map.xml
Add Sync for Reddit Pro icon to match free version's icon.
> Add Sync for Reddit Pro

- app/src/main/res/xml/grayscale_icon_map.xml
This pull request includes:
- Sync for Reddit (Pro and Dev)
- Telegram (Beta and Web)
- Camera (GCam Mods)
> Link existing icons to variant packages of the app

- app/src/main/res/xml/grayscale_icon_map.xml
first ever pull request i am using github for first time hope its get success
> Map Miui Calculator icon to Existing Calculator icon

- app/src/main/res/xml/grayscale_icon_map.xml
Maped miui gallery and camera app icons
> Map Miui Gallery and Camera app icons

- app/src/main/res/xml/grayscale_icon_map.xml
Build debug APK
Fixes #79   phone app have been added
> Add phone app

- app/src/main/res/xml/grayscale_icon_map.xml
GCam mod link - [https://www.celsoazevedo.com/files/android/google-camera/dev-greatness/f/dl4/](url)
> Link `com.google.android.GoogleCamera.Cameight` to camera

- app/src/main/res/xml/grayscale_icon_map.xml
Use the existing calculator icon for Google calculator
> Added Google calculator

- app/src/main/res/xml/grayscale_icon_map.xml
> Fix the Google Meet icon not being themed

- app/src/main/res/xml/grayscale_icon_map.xml
com.huawei.photos
fixes #320 
com.huawei.hidisk
fixes #321
> Link two huawei apps

- app/src/main/res/xml/grayscale_icon_map.xml
* com.asus.camera is package name of Asus Camera on Asus zen ui
Signed-off-by: Shubh <vishwajitg471@gmail.com>
> Link Asus Camera to Camera Icon

- app/src/main/res/xml/grayscale_icon_map.xml
> Link `@drawable/camera` to “com.hmdglobal.camera2” package

- app/src/main/res/xml/grayscale_icon_map.xml
> Link @drawable/camera to com.sonyericsson.android.camera package

- app/src/main/res/xml/grayscale_icon_map.xml
1. File Manager - [Linked @drawable/files to com.android.filemanager](https://github.com/LawnchairLauncher/lawnicons/commit/50bf6a5edd2ad8e3a901831a3be0a37850c8cd17)
2. Calculator - [Linked @drawable/calculator to com.android.bbkcalculator](https://github.com/LawnchairLauncher/lawnicons/commit/4648d7f1f09cbecf7d5f9faf5b0b98301b23ff5f)
3. Gallery - [Linked @drawable/gallery to com.vivo.gallery](https://github.com/LawnchairLauncher/lawnicons/commit/ad4ae31cf0a5bcd9ff76ca9824eac7c42e05fcf6)
4. Sound Recorder - [Linked @drawable/recorder to com.android.bbksoundrecorder](https://github.com/LawnchairLauncher/lawnicons/commit/b37c2cc4e17e3dbacb8da3112eef3d58fe15d260)
**Picture:**  After & Before
> Linked Vivos File Manager, Calculator, Gallery and Sound Recorder to exisiting drawables

- app/src/main/res/xml/grayscale_icon_map.xml
Adds support for LG's stock camera app
> Link @drawable/camera to com.lge.camera package

- app/src/main/res/xml/grayscale_icon_map.xml
Signed-off-by: akirasupr <vishal.rockstar7011@gmail.com>
> Link `@drawable/magisk` to “com.thehitman7.cygisk” package

- app/src/main/res/xml/grayscale_icon_map.xml
Adds support for the MWP GCam mod
> Link `@drawable/camera` to `com.GoogleCamera.mwp84`

- app/src/main/res/xml/grayscale_icon_map.xml
Linked the Syncthing icon to Syncthing-Fork
> Link `@drawable/syncthing` to `com.github.catfriend1.syncthingandroid`

- app/src/main/res/xml/grayscale_icon_map.xml
Hi, `grayscale_icon_map.xml` is a major file for everyone adding new icons and since it's a mess I sorted every line alphabetically so that it's easier to navigate and add future icons :)
This moved a lot of lines in the file so it may cause some conflicts with existing PRs.
> Sorting `grayscale_icon_map.xml` alphabetically

- app/src/main/res/xml/grayscale_icon_map.xml
Removed duplicated icon map for WhatsApp Business and fixed the package name for myXL.
> Minor fixes in the grayscale_icon_map.xml file

- app/src/main/res/drawable/youtube_revanced.xml
- app/src/main/res/xml/grayscale_icon_map.xml
add an icon for YouTube ReVanced
before:
after:
> Add YouTube ReVanced icon

- app/src/main/res/drawable/yandex.xml
- app/src/main/res/xml/grayscale_icon_map.xml
- svgs/yandex.svg
Hi there! It's my first time adding icons to Lawnicons, so I'm very excited of contributing this great project!
* Yandex (`ru.yandex.searchplugin`)
> Added 1 new icon!

- .github/workflows/build_debug_apk.yml
- .github/workflows/build_release_apk.yml
https://github.com/actions/setup-python/releases/tag/v4.0.0
https://github.com/actions/setup-python/releases/tag/v4.2.0
> Bump actions/setup-python to v4

- app/src/main/res/drawable/sliceit.xml
- app/src/main/res/xml/grayscale_icon_map.xml
- svgs/sliceit.svg
Added icon for [Slice](https://play.google.com/store/apps/details?id=indwin.c3.shareapp).
* Slice (`indwin.c3.shareapp`)
NA
NA
> Add Slice 

- app/src/main/res/drawable/ar_zone.xml
- app/src/main/res/drawable/swiggy.xml
- app/src/main/res/xml/grayscale_icon_map.xml
- svgs/ar_zone.svg
- svgs/swiggy.svg
* com.samsung.android.arzone
* in.swiggy.android (https://play.google.com/store/apps/details?id=in.swiggy.android)
* sarangal.packagemanager (https://play.google.com/store/apps/details?id=sarangal.packagemanager)
Fixes #(issue) 
* Samsung AR Zone(com.samsung.android.arzone)
* Swiggy (`in.swiggy.android`)
> Add AR Zone

- .github/workflows/build_debug_apk.yml
- .github/workflows/build_release_apk.yml
- app/build.gradle.kts
- gradle.properties
> Speed up a bit

- app/src/main/res/xml/grayscale_icon_map.xml
* App Name (linked `air.com.unit9.bkFrApp` to `@drawable/burger_king`)
> Link `air.com.unit9.bkFrApp` (French bk app) to `burger_king` icon

- app/build.gradle.kts
- build.gradle.kts
https://github.com/JetBrains/kotlin/releases/tag/v1.7.20
https://developer.android.com/jetpack/androidx/releases/compose-compiler#1.3.2
> Kotlin 1.7.20

- app/src/main/res/xml/grayscale_icon_map.xml
Link com.google.android.GoogleCameraLMC to Google camera
Fixes #(issue) 
*GCam (`com.google.android.GoogleCameraLMC`)
> Link Gcam LMC version

- app/src/main/res/xml/grayscale_icon_map.xml
Linked icons for the apps freezer (f.f.freezer) and QR & Barcode Scanner (org.barcodescanner) Also removed a space that messed up my OCD :p
removed a space before <icon at line 686
* Freezer (linked f.f.freezer to @drawable/deezer)
* QR & Barcode Scanner (linked org.barcodescanner to @drawable/qr_reader)
> Linked 2 icons and a very small cleanup :)

- app/src/main/res/xml/grayscale_icon_map.xml
Fixes #(issue)
* Business Kalendar (linked `com.appgenix.bizcal` to `@drawable/calendar`)
> added  Business Kalendar 2 as Link

- app/src/main/res/xml/grayscale_icon_map.xml
* Next DB Navigator (linked `com.deutschebahn.app.android` to `@drawable/db_navigator`)
> Link Next DB Navigator to DB Navigator

- app/src/main/res/xml/grayscale_icon_map.xml
✅ : General change (non-breaking change that doesn't fit the above categories like copyediting)
Unlink geometric weather from weather
> Unlink geometric weather from weather

- app/src/main/res/xml/grayscale_icon_map.xml
✅ : General change (non-breaking change that doesn't fit the above categories like copyediting)
> Remove duplicate

- app/src/main/res/drawable/dealabs.xml
- app/src/main/res/xml/grayscale_icon_map.xml
- svgs/dealabs.svg
Add dealabs icon. I remade the icon I first made months ago here #475 (I just forgot I closed the pr 😅)
This time I double checked the icon size, no more "144px for squares" fixes needed (hopefully) !
* Dealabs(`com.dealabs.apps.android`)
> add dealabs icon

- settings.gradle.kts
✅ : General change (non-breaking change that doesn't fit the above categories like copyediting)
> Bump com.gradle.enterprise from 3.11.2 to 3.11.3

- app/src/main/res/drawable/bhim.xml
- app/src/main/res/xml/grayscale_icon_map.xml
- svgs/bhim.svg
Added Icon for BHIM UPI app
* BHIM (`in.org.npci.upiapp`)
> BHIM UPI app icon addition

- app/src/main/res/drawable/mi_freeform.xml
- app/src/main/res/xml/grayscale_icon_map.xml
- svgs/mi_freeform.svg
Just installed an LSPosed module recently and thought of theming the icon for the app. The app is called Mi Freeform, an LSPosed Sui module that enables MIUI's mini-window feature in AOSP ROMs. Also made some minor change to the `grayscale_icon_map.xml`
* Mi Freeform (`com.sunshine.freeform`)
> Added Mi Freeform

- .editorconfig
- app/src/main/res/xml/grayscale_icon_map.xml
> Sort lines alphabetically in grayscale_icon_map.xml

- app/src/main/res/xml/grayscale_icon_map.xml
https://github.com/prathameshmm02/Calculator-inator
https://www.celsoazevedo.com/files/android/google-camera/dev-burial/
https://play.google.com/store/apps/details?id=app.grapheneos.pdfviewer.play
* Calculator-inator (linked `com.inator.calculator` to `@drawable/calculator`)
* Camera (linked `com.GoogleCamera.Burial` to `@drawable/camera`)
* PDF Viewer (linked `app.grapheneos.pdfviewer` to `@drawable/grapheneos_pdf`)
> Link 3 icons

- app/src/main/res/xml/grayscale_icon_map.xml
* Fork Client - fork of Telegram messenger (linked `org.forkgram.messenger` to `@drawable/telegram`)
* InnerTune - YouTube Music client (linked `com.zionhuang.music` to `@drawable/mi_music`)
* Simple Dialer (linked `com.simplemobiletools.dialer` to `@drawable/dialer`)
* Simple Voice Recorder (linked `com.simplemobiletools.voicerecorder` to `@drawable/Recorder`)
> Add 4 new icon links

- app/src/main/res/xml/grayscale_icon_map.xml
Link another SmartPack-Kernel Manager
* App Name (linked `com.smartpack.kernelmanager` to `@drawable/smartpack_kernel_manager`)
*  App Name (linked `com.smartpack.kernelmanager.pro` to `@drawable/smartpack_kernel_manager`)
> Link another SmartPack-Kernel Manager

- app/src/main/res/xml/grayscale_icon_map.xml
Link Pizza Hut Germany
* App Name (linked `com.pizzahut.germany` to `@drawable/pizza_hut`)
> Link pizza hut germany

- app/src/main/res/xml/grayscale_icon_map.xml
Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>
Fixes #(issue)
> Fix mapping for disney app

- app/src/main/res/xml/grayscale_icon_map.xml
> Add Vodafone Links

- app/src/main/res/drawable/traderepublic.xml
- app/src/main/res/xml/grayscale_icon_map.xml
- svgs/traderepublic.svg
Adding icon for Trade Republic
* App Name (`de.traderepublic.app`)
* App Name (linked `de.traderepublic.app` to `@drawable/traderepublic`)
> Add icon for Trade Republic

- app/src/main/res/drawable/hiby_music.xml
- app/src/main/res/xml/grayscale_icon_map.xml
- svgs/hiby_music.svg
https://play.google.com/store/apps/details?id=com.hiby.music
* App Name (`com.hiby.music`)
> Add icon for Hiby Music

- app/src/main/res/xml/grayscale_icon_map.xml
https://play.google.com/store/apps/details?id=de.uni_potsdam.hpi.openmensa
https://f-droid.org/packages/us.spotco.maps/
* App Name (linked `de.uni_potsdam.hpi.openmensa` to `@drawable/cookbook`)
* App Name (linked `us.spotco.maps` to `@drawable/maps`)
> Link OpenMensa & GMaps WV

- app/build.gradle.kts
Link https://github.com/LawnchairLauncher/lawnchair/pull/3156.
https://android-developers.googleblog.com/2022/10/whats-new-in-jetpack-compose.html https://developer.android.com/jetpack/androidx/releases/compose
> Use bom to manage Compose versions

- app/src/main/res/xml/grayscale_icon_map.xml
https://play.google.com/store/apps/details?id=com.adobe.adobephotoshopfix
https://play.google.com/store/apps/details?id=com.adobe.lrmobile
https://play.google.com/store/apps/details?id=com.adobe.photoshopmix
https://play.google.com/store/apps/details?id=com.adobe.psmobile
https://play.google.com/store/apps/details?id=com.mt.mtxx.mtxx
https://play.google.com/store/apps/details?id=com.niksoftware.snapseed
https://play.google.com/store/apps/details?id=photo.editor.polarr
> Link some photo editors

- CONTRIBUTING.md
Changes CONTRIBUTING.md in few places to improve clarity a bit.
> Small wording changes in CONTRIBUTING.md

- app/src/main/res/xml/grayscale_icon_map.xml
Fixes #(issue)
* eu.kanade.tachiyomi.debug
> Add new Tachiyomi link

- app/src/main/res/xml/grayscale_icon_map.xml
Fixes: https://github.com/LawnchairLauncher/lawnicons/commit/73169a33dcb32c82d2a2ccc820f8193a89a0bf6d
Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>
Fixes #(issue)
> Fix YouTube VR package name

- app/src/main/res/drawable/beeper.xml
- app/src/main/res/xml/grayscale_icon_map.xml
- svgs/beeper.svg
Add Icon for Beeper Chat: https://www.beeper.com
Preview:
* App Name (`com.beeper.chat`) - added from icon request form
* App Name (linked `com.beeper.chat` to `@drawable/beeper`)
> Add Icon for Beeper

- app/build.gradle.kts
- build.gradle.kts
Links https://github.com/LawnchairLauncher/lawnchair/pull/3257.
https://github.com/JetBrains/kotlin/releases/tag/v1.8.0
https://developer.android.com/jetpack/androidx/releases/compose-compiler#1.4.0
> Kotlin 1.8 and Compose compiler 1.4.0

- app/src/main/res/xml/grayscale_icon_map.xml
Follow up https://github.com/LawnchairLauncher/lawnchair/pull/3255.
* Lawnchair Debug (linked `app.lawnchair.debug` to `@drawable/lawnchair`)
> Link Lawnchair debug to Lawnchair

- CONTRIBUTING.md
- app/assets/appfilter.xml
- svgs/hacki.svg
Add Icon for [Hacki](https://github.com/Livinglist/Hacki)
* Hacki (`com.jiaqifeng.hacki`)
Contribution documentation suggests using `-E` when using `grep` on Linux.
Extended expression syntax is not used, so this flag is not needed.
Some older systems do not support the `-E` flag.
> Add Icon for Hacki

- app/assets/appfilter.xml
- svgs/v2rayng.svg
https://play.google.com/store/apps/details?id=com.v2ray.ang
* v2rayNG (`com.v2ray.ang`)
* v2rayNG (linked `com.v2ray.ang` to `@drawable/v2rayng`)
> Add icon for v2rayNG

- app/assets/appfilter.xml
link Hiby Music & Michelin Guide
Fixes #(issue)
* hiby music (linked `com.hiby.music` to `@drawable/hiby_music`)
* michelin guide (linked `com.viamichelin.android.gm21` to `@drawable/michelin_guide`)
> Relink 2 apps

- app/assets/appfilter.xml
Add links to new icons
* 1password 
* Slice
> Add new icon links

- app/assets/appfilter.xml
- svgs/rocketbook.svg
https://play.google.com/store/apps/details?id=com.rb.rocketbook
* App Name (`com.rb.rocketbook`)
* App Name (linked `com.rb.rocketbook` to `@drawable/rocketbook`)
> Add icon for Rocketbook

- app/assets/appfilter.xml
:white_check_mark:  General change (non-breaking change that doesn't fit the above categories like copyediting)
> Update componenet for Messages and Freecharge

- app/assets/appfilter.xml
Add the missing components for ScooterHacking Utility and Nine Dash
https://github.com/LawnchairLauncher/lawnicons/pull/1046
✅ : Bug fix (non-breaking change which fixes an issue)
> Add missing components from PR #1046

- app/assets/appfilter.xml
- app/src/main/res/xml/grayscale_icon_map.xml
This can be merged after https://github.com/LawnchairLauncher/lawnicons/pull/1066
Add pizza hut germany, tapatalk, termux api and styling into appfilter and delete the entries in grayscale from PR 1066
✅  : General change (non-breaking change that doesn't fit the above categories like copyediting)
> Add new links to appfilter.xml

- app/assets/appfilter.xml
Link for F-Droid version of odysee.
* App Name (linked `com.odysee.floss` to `@drawable/odysee`)
> Link odysee-floss

- app/assets/appfilter.xml
Linked the innertune debug apk filename with innertune itself. Icon is no different for debug version
> Link innertune debug

- app/assets/appfilter.xml
- svgs/akku_alarm.svg
- svgs/bing.svg
- svgs/evoland.svg
- svgs/payback.svg
Should be sorted correctly :)
I used `cat appfilter.xml | sort -t '"' -k 4 > appfilter_tmp.xml`
> Add bing, payback &evoland, link onvista

- app/assets/appfilter.xml
- app/src/main/res/xml/grayscale_icon_map.xml
Link magisk delta
✅ : General change (non-breaking change that doesn't fit the above categories like copyediting)
* Magisk Delta (linked `io.github.huskydg.magisk` to `@drawable/magisk`)
> Link magisk delta

- app/assets/appfilter.xml
- svgs/tk.svg
Icon for https://play.google.com/store/apps/details?id=de.tk.tkapp
* App Name (`de.tk.tkapp`)
* App Name (linked `de.tk.tkapp` to `@drawable/tk`)
> Add icon for TK

- app/assets/appfilter.xml
Fix activities for issue https://github.com/LawnchairLauncher/lawnicons/issues/951
Fixes #(issue)
https://github.com/LawnchairLauncher/lawnicons/issues/951
✅ : Bug fix (non-breaking change which fixes an issue)
> Fix activities

- app/assets/appfilter.xml
> Add link MGC Camera 8.7.250

- app/assets/appfilter.xml
- svgs/kvaesitso_icons.svg
Add Kvaesitso-Icons
https://github.com/daywalk3r666/Kvaesitso-Icons
✅  Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
* Kvaesitso-Icons (`de.kvaesitso.icons`)
> Add Kvaesitso-Icons

- app/assets/appfilter.xml
- svgs/translate_you.svg
> Add translate you and swap superfreezz

- app/assets/appfilter.xml
Link YouTube ReVanced Extended, and YouTube Music ReVanced Extended
✅ General change (non-breaking change that doesn't fit the above categories like copyediting)
* YouTube Music ReVanced Extended (linked `app.rvx.android.apps.youtube.music` to `@drawable/youtube_music`)
* YouTube ReVanced Extended (linked `app.rvx.android.youtube` to `@drawable/revanced_extended`)
> Link ReVanced Extended

- app/assets/appfilter.xml
Added icon to the Vendetta discord mod
* App Name (`dev.beefers.vendetta')
> Add discord icon to Vendetta app

- app/assets/appfilter.xml
- svgs/george.svg
* George Österreich/Austria (`at.erstebank.george`)
> Add George Icon

- .github/icontool_guide.md
- icontool.py
Exactly what it says on the title. Grouped stuff into functions, and organized a lot of stuff to make it easier to read. Also used subcommands.
So from:
```sh
python3 icontool.py -s /path/to/icon.svg -c com.app.app/com.app.app.appActivity -n "App Name"
```
To:
```sh
python3 icontool.py add /path/to/icon.svg com.app.app/com.app.app.appActivity "App Name"
```
I'll work on documentation, and optimizing the sorting/adding to xml code maybe tommorow.
cc @thismoon, since i can't assign you to this
✅ General change (non-breaking change that doesn't fit the above categories like copyediting)
> Refine icontool.py

- app/assets/appfilter.xml
Mapped Odialer to google phone app
* ODialer (linked `com.oplus.dialer` to `@drawable/google_phone`)
> Link ODialer to Google phone 

- app/assets/appfilter.xml
* App Name (linked `in.startv.hotstar` to `@drawable/hotstar`)
> Added hotstar new activity

- app/assets/appfilter.xml
Added 4 new item entries and edited existing 2 entries from same developer. Removed `HomeActivity` because it does not exists in the app.
✅ General change (non-breaking change that doesn't fit the above categories like copyediting)
* Qur'an Bangla (linked `com.andi.alquran.bangla` to `@drawable/quran`)
* Qur'an French (linked `com.andi.alquran.francais` to `@drawable/quran`)
* Qur'an Melayu (linked `com.andi.alquran.melayu` to `@drawable/quran`)
* Qur'an Urdu (linked `com.andi.alquran.urdu` to `@drawable/quran`)
> Link 4 apps to Quran

- app/assets/appfilter.xml
Added two My Airtel activity entries.
✅ General change (non-breaking change that doesn't fit the above categories like copyediting)
* My Airtel (linked `net.omobio.airtelsc` to `@drawable/myairtel`)
> Link My Airtel to Airtel

- app/assets/appfilter.xml
- svgs/bob.svg
- svgs/conversations.svg
- svgs/kleinanzeigen.svg
- svgs/rewe.svg
> add new kleinanzeigen logo

- app/assets/appfilter.xml
Link 4 new apps and relink 1 app to dialer.
* Phone (linked `com.android.contacts` to `@drawable/dialer`)
* Clock (linked `com.coloros.alarmclock` to `@drawable/clock`)
* Music (linked `com.oppo.music` to `@drawable/yandex_music`)
* Sound Recorder (linked `com.coloros.soundrecorder` to `@drawable/recorder`)
* Videos (linked `com.coloros.video` to `@drawable/generic_player`)
> Link 5 ColorOS apps

- app/assets/appfilter.xml
Linked 4 icons
* OnePlus Gallery (linked `com.oneplus.gallery` to `@drawable/gallery`)
* Aplayer (linked `remix.myplayer` to `@drawable/music`)
* Vanilla (linked `com.kyant.vanilla` to `@drawable/music`)
* CherryGram (linked `uz.unnarsx.cherrygram` to `@drawable/Telegram`)
> Link 4 icons

- app/assets/appfilter.xml
Woa, can't believe it's already been 6 months since my last contribution...
Lots of things changed here it's nice to see 👍
Link `com.dot.gallery` to `gallery.svg`
(https://github.com/IacobIonut01/Gallery)
* Gallery (linked `com.dot.gallery` to `@drawable/gallery`)
> link gallery icon to a new gallery app

- app/assets/appfilter.xml
- svgs/rtl.svg
- svgs/yuzu.svg
> add yuzu, rtl & link paperless mobile

- app/assets/appfilter.xml
- svgs/bandido.svg
- svgs/evmap.svg
> add bandido & evmap

- app/assets/appfilter.xml
* Aniyomi (linked `xyz.jmir.tachiyomi.mi.debug` to `@drawable/aniyomi`)
> link `aniyomi.debug` to Aniyomi icon

- app/assets/appfilter.xml
- svgs/flow_hexes.svg
✅  Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
* Flow Free: Hexes (`com.bigduckgames.flowhexes`)
> Add flow_hexes icon

- .github/workflows/first_pr_interaction.yml
Read the title. Feedback for the message contents is welcome.
> Create message for first time contributors

- settings.gradle.kts
> Remove resolutionStrategy for OSS plugin

- app/assets/appfilter.xml
> add closing curly brace

- app/assets/appfilter.xml
> Add new Activity for Tinder

- app/assets/appfilter.xml
A little while ago Gloom updated its package name, this small PR exists just to update it.
> Correct package name for Gloom

- app/build.gradle.kts
- app/src/main/kotlin/app/lawnchair/lawnicons/ui/components/home/SearchBar.kt
- app/src/main/kotlin/app/lawnchair/lawnicons/ui/destination/About.kt
- app/src/main/kotlin/app/lawnchair/lawnicons/ui/destination/Acknowledgement.kt
- app/src/main/kotlin/app/lawnchair/lawnicons/ui/destination/Acknowledgements.kt
- app/src/main/kotlin/app/lawnchair/lawnicons/ui/destination/Contributors.kt
- app/src/main/kotlin/app/lawnchair/lawnicons/ui/destination/Home.kt
- app/src/main/kotlin/app/lawnchair/lawnicons/viewmodel/ContributorsViewModel.kt
- gradle.properties
- svg-processor/src/main/kotlin/app/lawnchair/lawnicons/helper/ConfigProcessor.kt
> Target 34 & Minor cleanups

- gradle.properties
> Remove lint version overriding

- app/build.gradle.kts
> Use reporting extension

- app/assets/appfilter.xml
- svgs/phonetrack.svg
Adds icon for nextcloud PhoneTrack app.
* App Name (`net.eneiluj.nextcloud.phonetrack`)
> Add PhoneTrack

- app/assets/appfilter.xml
- svgs/bhagavad_gita.svg
- svgs/omnivore.svg
Added 2 new icons and made the entries in xml.
* Bhagavad Gita (`com.wirelessalien.android.bhagavadgita`)
* Omnivore (`app.omnivore.omnivore`)
> Icon addition (2)

- .github/workflows/build_debug_apk.yml
- .github/workflows/build_release_apk.yml
- .github/workflows/check_kotlin_style.yml
https://docs.gradle.org/8.3/release-notes.html?#full-support-for-java-20
> Use Java 20 on CI

- app/assets/appfilter.xml
- svgs/anilabx.svg
- svgs/dooz.svg
Add 2 app icons
* AniLabX (`com.crazyxacker.apps.anilabx3`) - added from icon request form
* Dooz (`io.github.yamin8000.dooz`)
> add 2 icons

- app/build.gradle.kts
> Capitalized variant name

- app/assets/appfilter.xml
- svgs/txd_tool.svg
* TXD Tool (`com.viseksoftware.txdw`)
> add TXD Tool icon

- app/assets/appfilter.xml
- svgs/exodus.svg
E
Add exodus privacy app (https://exodus-privacy.eu.org/en/)
* Exodus (`org.eu.exodus_privacy.exodusprivacy`)
> Add Exodus

- .editorconfig
- build.gradle.kts
https://github.com/pinterest/ktlint/releases/tag/1.0.1
> Ktlint 1.0.1

- app/assets/appfilter.xml
* App Name (linked `ytm.rvx.noname.exe` to `@drawable/youtube_music`)
* App Name (linked `yt.rvx.noname.exe` to `@drawable/revanced_extended`)
I've added several lines into the linking XML because I don't really know which activity is the main activity for RVX and because there are also several lines for the old RVX linkage.
**Old RVX links:**
```xml
<item component="ComponentInfo{app.rvx.android.youtube/com.google.android.youtube.app.honeycomb.Shell$HomeActivity}" drawable="revanced_extended" name="YouTube ReVanced Extended" />
<item component="ComponentInfo{app.rvx.android.youtube/com.google.android.youtube.app.honeycomb.ShellHomeActivity}" drawable="revanced_extended" name="YouTube ReVanced Extended" />
```
**Links I've added:**
```xml
<item …
```
> Link new ReVanced Extended package name

- app/assets/appfilter.xml
Updated the name of DB Navigator's activity. This time I also didn't remove the old activity name.
> Updated DB Navigator activity name

- app/assets/appfilter.xml
- svgs/moj_orange.svg
> Add Mój Orange

- app/assets/appfilter.xml
All icons linked to `@drawable/burger_king`.
Burger King (`ph.burgerking/com.usemenu.MenuAndroidApplication.SplashActivity`)
Burger King (`bo.burgerking/com.usemenu.MenuAndroidApplication.SplashActivity`)
Burger King (`burgerking.com.br.appandroid/burgerking.com.br.appandroid.splash.SplashActivity_`)
Burger King (`burgerking.com.br.appandroid/burgerking.com.br.appandroid.splash.SplashActivityAlias`)
Burger King (`com.ajvierci.burgerking/com.ajvierci.burgerking.MainActivity`)
Burger King (`com.bzbs.burgerking/com.bzbs.burgerking.ui.splash.SplashActivity`)
Burger King (`com.crazycake.burgerkingchile/com.usemenu.MenuAndroidApplication.SplashActivity`)
Burger King (`com.emn8.mobilem8.nativeapp.bkca/com.emn8.mobilem8.nativeapp.bkca.MainActivity`)
Burger King …
> +19 links for Burger King

- README.md
Fixed a link in the description that stopped opening after #1587.
> Fixing a link in the description

- app/assets/appfilter.xml
* HIT (linked `com.lionwood.nitwrap` to `com.lionwood.nit`)
> Linked 1 icon

- app/src/main/kotlin/app/lawnchair/lawnicons/ui/destination/About.kt
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-mr/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
Made "External Links" a translatable String and added the Polish Translation.
"Icon Request Form" remains as the last String which I couldn't get to work.
✅ : General change (non-breaking change that doesn't fit the above categories, such as copyediting)
> Make "External Links" a translatable String

- app/assets/appfilter.xml
Link Gloom debug variant to gloom.svg
* Gloom Debug (linked `com.materiiapps.gloom.debug` to `@drawable/gloom`)
> Link Gloom debug apk

- app/assets/appfilter.xml
- app/src/main/res/values-id/strings.xml
> Add Indonesian translation

- app/src/main/res/values-fr/strings.xml
Add french translation for `request_form`
> Add request_form french translation

- app/assets/appfilter.xml
- svgs/taxi_coop.svg
Add icon for Taxi Coop (https://www.taxicoop.ca/, https://play.google.com/store/apps/details?id=ca.skex.taxicoop5191)
* Taxi Coop (`ca.skex.taxicoop5191`)
> Add icon for Taxi Coop

- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-mr/strings.xml
Added translation of "Icon Request Form" in Hindi & Marathi
✅ General change (non-breaking change that doesn't fit the above categories, such as copyediting)
> Updated Hindi & Marathi Translations 

- README.md
> Adding a hint in case of icon redesign

- app/assets/appfilter.xml
- svgs/pleco.svg
* Pleco (`com.pleco.chinesesystem`)
* Mój T-Mobile (linked `pl.tmobile.miboa` to `@drawable/my_tmobile`)
> Add icon for Pleco, link Mój T-Mobile to a drawable

- app/assets/appfilter.xml
Fulfilling requests.
App Market (`com.heytap.market/com.oppo.cdo.ui.external.desktop.DeskHotAppActivity`)
App Market (`com.heytap.market/com.oppo.cdo.ui.external.desktop.DeskHotGameActivity`)
Camera (`com.google.android.GoogleCamera3/com.android.camera.CameraLauncher`)
Discord (`com.discord/com.discord.main.MainBrandDark`)
Files (`com.coloros.filemanager/com.coloros.filemanager.filerefactor.ui.main.MainActivity`)
HeyTap Music (`com.heytap.music/com.nearme.music.splash.SplashActivity`)
Kindle (`com.amazon.kindle/com.amazon.kindle.UpgradePage`)
Lawnchair (`app.lawnchair.debug/leakcanary.internal.activity.LeakLauncherActivity`)
OnePlus Community (`net.oneplus.forums/com.oplus.community.activity.LauncherActivity`)
Recorder (`com.coloros.soundrecorder/com.soundrecorder.browsefile.BrowseFile`) …
> +18 links: Discord, System apps, Youtube

- CONTRIBUTING.md
GitHub deleted the previous video, so I uploaded the new one separately. 
> Replaced the broken link to a video guide on how to fill out the requests form

- app/src/main/AndroidManifest.xml
Copy-paste some of them from https://github.com/PapirusDevelopmentTeam/papirus_icons/blob/b901e193c802dc9821acda30b5c7bd5f240bdaf5/app/src/main/AndroidManifest.xml#L114-L184
> Support more launchers

- app/assets/appfilter.xml
Another couple hundred missed links.
AccuWeather (`com.accuweather.android/com.accuweather.android.AccuWeather` → `accuweather.svg`)
AccuWeather (`com.accuweather.android/com.accuweather.android.MainActivity` → `accuweather.svg`)
AccuWeather (`com.accuweather.android/com.accuweather.android.MainMenuActivity` → `accuweather.svg`)
Action Launcher (`com.actionlauncher.playstore/com.actionlauncher.rocket.app.ActivityPicker` → `action_launcher.svg`)
Action Launcher (`com.actionlauncher.playstore/com.android.launcher3.WallpaperCropActivity` → `action_launcher.svg`)
Action Launcher (`com.actionlauncher.playstore/com.android.launcher3.WallpaperPickerActivity` → `action_launcher.svg`)
AirBrush (`com.magicv.airbrush/com.magicv.airbrush.StartupActivity` → `airbrush.svg`)
Amazon Appstore …
> +265 links

- send_notifications.py
This fix is slightly modified to exit with code 1 instead of return because this script "block" isn't a function.
cc: @Goooler 
Fixes #(issue)
> Port fix from Lawnchair repository

- app/assets/appfilter.xml
Linked Fossify apps. Not all of them are released yet, so I will check for package name compatibility once they are.
None
Fossify Launcher (`org.fossify.applauncher` → `app_launcher.svg`)
Fossify Calculator (`org.fossify.calculator` → `calculator.svg`)
Fossify Calendar (`org.fossify.calendar` → `simple_calendar.svg`)
Fossify Camera (`org.fossify.camera` → `camera.svg`)
Fossify Clock (`org.fossify.clock` → `clock.svg`)
Fossify Contacts (`org.fossify.contacts` → `contacts.svg`)
Fossify Draw (`org.fossify.draw` → `pencil.svg`)
Fossify File Manager (`org.fossify.filemanager` → `files.svg`)
Fossify Gallery (`org.fossify.gallery` → `simple_gallery.svg`)
Fossify Keyboard (`org.fossify.keyboard` → `keyboard.svg`)
Fossify Messages (`org.fossify.messages` → `messages.svg`)
Fossify Music Player …
> Link Fossify apps

- send_notifications.py
Uploads CI builds to the Discord channel.
> Implement CI notifications for Discord

- app/assets/appfilter.xml
I added 2 links fround in https://docs.google.com/spreadsheets/d/1AXc9EDXA6udZeGROtB5nuABjM33VluGY_V24tIzHaKc/edit?resourcekey#gid=507544179 that matched already created icons
App Name (`de.burgerking.kingfinder/rbi.android.app.MainActivity` → `burger_king.svg`)
App Name (`com.microsoft.xboxone.smartglass.beta/com.microsoft.xbox.MainActivity` → `xbox.svg`)
> Add 2 links

- README.md
> The link to popular requests now leads to the summary

- app/assets/appfilter.xml
Ayugram (`org.telegram.messenger/com.exteragram.messenger.DefaultIcon` → `ayugram.svg`)
> Link Ayugram

- README.md
> Minor change to description

- app/assets/appfilter.xml
Linked LineageOS Glimpse to gallery
Gallery (`org.lineageos.glimpse` → `gallery.svg`)
> Link LineageOS Glimpse to gallery

- app/build.gradle.kts
- app/proguard-rules.pro
- app/src/main/kotlin/app/lawnchair/lawnicons/api/ApiModule.kt
https://github.com/square/retrofit/releases/tag/2.10.0
> Retrofit 2.10.0

- .github/PULL_REQUEST_TEMPLATE/icon_addition.md
- CONTRIBUTING.md
— the wording in the template for adding icons has become wider to fit PRs that only have links.
— explained in the TL;DR section how to maintain visual balance.
> Simplified the wording in the guidelines and in the template for adding icons

- CONTRIBUTING.md
There are the same issues in different reviews, so I added a suggestion to read reviews before starting to create icons. I also specified which graphic editors are suitable for working on icons and what the TL;DR section refers to.
> Added a brief recommendation on creating icons to the TL;DR section

- app/assets/appfilter.xml
Linked Gadgetbridge Nightly to gadgetbridge
Gadgetbridge Nightly (`nodomain.freeyourgadget.gadgetbridge.nightly` → `gadgetbridge.svg`)
> Link Gadgetbridge Nightly

- app/assets/appfilter.xml
YTDLnis (`com.deniscerri.ytdl/com.deniscerri.ytdl.Default` → `ytdlnis.svg`)
> Link latest YTDLnis

- CONTRIBUTING.md
> Added a link to Google Play for the IconRequest app

- app/assets/appfilter.xml
Fulfilling requests.
McDonald's (`com.mcdonalds.mobileapp/com.mcdonalds.mobileapp.redesign.MainActivity` → `mcdonalds.svg`)
Rider (`com.ketchapp.rider/com.ansca.corona.CoronaActivity` → `rider_ketchapp.svg`)
ScreenStream (`info.dvkr.screenstream/info.dvkr.screenstream.ui.activity.AppActivity` → `screen_stream.svg`)
> +3 links and simplification of names

- CONTRIBUTING.md
> Minor changes in TL;DR section of the Lawnicons guidelines

- README.md
> Edited the wording of the description to make it shorter

- app/build.gradle.kts
- app/src/main/res/resources.properties
Allow the user to switch language using Android App Settings
This port over feature from Lawnchair Launcher `kebab` into Lawnchair Lawnicons
* https://github.com/LawnchairLauncher/lawnchair/pull/4312
Co-authored-by: @Goooler 
> Enable automatic per-app language support

- CONTRIBUTING.md
- README.md
IconRequest app has been updated a bit, so the past video has become irrelevant.
> Updated the video guide on how to request icons

- app/assets/appfilter.xml
Fulfilling requests.
Bugjaeger Premium (`eu.sisik.hackendebug.full/eu.sisik.hackendebug.SplashActivity` → `bugjaeger.svg`)
iMe (`com.iMe.android/org.telegram.ui.LaunchActivityKeyIcon` → `ime.svg`)
YouTube ReVanced (`app.revanced.android.youtube/com.google.android.youtube.app.honeycomb.Shell` → `youtube_revanced.svg`)
Dialer (`com.android.contacts/com.android.contacts.activities.TwelveKeyDialer`)
> Fix for a dialer + 3 links

- .github/PULL_REQUEST_TEMPLATE/icon_addition.md
I changed hints of the icon addition template a little, because some contributors get confused when they decide where and what to write.
> Updating the icon addition template

- .github/PULL_REQUEST_TEMPLATE/icon_addition.md
> Small change to the hints in the icon addition template

- app/assets/appfilter.xml
Bunny (`io.github.pyoncord.app/com.discord.main.MainDefault` → `discord.svg`)
> Link Bunny

- .github/icon_checklist.md
- CONTRIBUTING.md
I'm clarifying some of the wording so that the guidelines are clearer and require fewer unnecessary actions.
> Clarifying the wording in the guidelines

- .github/icon_checklist.md
> Clarified the instructions for finding the visual center of an icon

- .github/ISSUE_TEMPLATE/icon_rebrand.yml
- README.md
+ one-line example
+ new link in the repository description
> Additional changes for the icon update template

- app/assets/appfilter.xml
- svgs/claude_by_anthropic.svg
Added 1 icon and updated 1 icon link
If the icon is not suitable for Lawnicons designed in this way, one alternative is to use the Anthropic logo instead:
Claude by Anthropic (`com.anthropic.claude`)
ShizuTools (`com.legendsayantan.adbtools`) `ashell.svg` --> `system_ui_tuner.svg` (Closes #2237)
> + 1 icon, + 1 update

- app/src/main/kotlin/app/lawnchair/lawnicons/MainActivity.kt
Refs https://github.com/LawnchairLauncher/lawnchair/pull/4659.
> Fix edge-to-edge on three-button nav bar

- CONTRIBUTING.md
Expanded the example of forming a line to add an icon and added a clarification about links.
> Clarified the process of adding and linking icons

- app/assets/appfilter.xml
Play Store submission
Lawnchair Launcher (Google Play Store 2) (`app.lawnchair.play/app.lawnchair.LawnchairLauncher` → `lawnchair`)
> Link Lawnchair Google Play Store package name

- .github/icon_checklist.md
- CONTRIBUTING.md
1. I made a note for PRs with icons so that there was enough time for a review without loss of quality.
2. I removed the checkboxes from the list for self-review. In practice, they are useless.
:white_check_mark:  General change (non-breaking change that doesn't fit the above categories, such as copyediting)
> Small refinements of the Lawnicons docs

- .github/icon_checklist.md
> Minor fix to the self-review list

- .github/PULL_REQUEST_TEMPLATE/icon_addition.md
- .github/icon_checklist.md
Practice has shown that the contributor's checklist does not affect the result in any way. I want to confirm or deny this.
> Simplifying the icon addition template

- README.md
I continue to align the badges.
> Fixing badges in the repo description

- README.md
> Minor badges fix

- app/assets/appfilter.xml
Revenge (`app.revenge/com.discord.main.MainDefault` → `discord.svg`)
> Link Revenge

- app/assets/appfilter.xml
Update the activity name for SimpleLogin in the icon link to the correct value
> Fix SimpleLogin link

- .github/ISSUE_TEMPLATE/icon_rebrand.yml
I refine the hints and remove unnecessary fields.
> Refinement of the template for requesting icon updates

- app/assets/appfilter.xml
Link the T-Life app to the T-Mobile icon
T-Life (`com.tmobile.tuesdays` → `tmobile.svg`)
> Link T-Life app to T-Mobile icon

- .github/ISSUE_TEMPLATE/icon_rebrand.yml
- .github/icon_checklist.md
- CONTRIBUTING.md
- README.md
I am correcting some errors and simplifying our templates.
> Error correction and copyediting

- app/assets/appfilter.xml
The Smart_Gigalife app (com.smart.consumer.app) got updated to have its classes to launch the app changed
New classes...
com.smart.consumer.app/.view.splash.OnboardingActivity
> update the appfilter.xml to have an icon that looks similar

- .github/ISSUE_TEMPLATE/icon_rebrand.yml
> Small update for the icon update template

- .github/ISSUE_TEMPLATE/icon_rebrand.yml
- README.md
#2493 
There is also a minor change for the icon update template.
> Removed the deleted form

- .github/ISSUE_TEMPLATE/config.yml
Added a hint to the issue template.
> Suspension of icon requests

- .github/ISSUE_TEMPLATE/config.yml
> Minor config.yml fix

- README.md
https:/\/apps.obtainium.imranr.dev/redirect?r=obtainium://add/https:/\/github.com/LawnchairLauncher/lawnicons ~~/~~
> Tiny change

- .github/ISSUE_TEMPLATE/config.yml
- CONTRIBUTING.md
- README.md
> fix: Request form and Discord link

- .github/ISSUE_TEMPLATE/icon_rebrand.yml
- README.md
> Copyediting

- .github/ISSUE_TEMPLATE/icon_rebrand.yml
> Minor copyediting (test)

- .github/ISSUE_TEMPLATE/icon_rebrand.yml
> Minor copyediting (test 2)

- .github/ISSUE_TEMPLATE/icon_rebrand.yml
> Minor copyediting

- README.md
> Minor copyediting fix

- .github/icon_checklist.md
> Minor fix for the common issues list

- app/src/main/res/values/colors.xml
This adds support for custom material color theming within Smart Launcher, see:
https://docs.smartlauncher.net/work-with-smart-launcher/icon-packs#specify-custom-material-colors
> Add better Smart Launcher integration

- CONTRIBUTING.md
Update contributing guidelines links
> Update contributing guidelines links

- README.md
> Increasing the relevance of the repository description

- README.md
Simplified the description to emphasize the Lawnicons design guidelines update and closing icon requests.
Once the Lawnicons design guidelines update is published, a different description will need to be made.
> Temporary description

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/icon_redesign.yml
- .github/PULL_REQUEST_TEMPLATE/general_change.md
- .github/PULL_REQUEST_TEMPLATE/icon_addition.md
- .github/icon_checklist.md
- README.md
Updating links and refining templates.
> Various copyediting

- .github/release.yml
> Link to the changelog in the Lawnicons Nightly release

- .github/release.yml
I'm trying to remove the "What's Changed" section.
> Correction for generating the Lawnicons Nightly changelog

- .github/release.yml
- .github/workflows/build_debug_apk.yml
Found 1 more option to simplify the changelog.
#2733 Root cause
> Update Lawnicons Nightly changelog

- .github/release.yml
- .github/workflows/build_debug_apk.yml
Reverts LawnchairLauncher/lawnicons#2741
> Revert "Update Lawnicons Nightly changelog"

- app/assets/appfilter.xml
A couple lines had trailing spaces in `name="..."`. I fixed them here.
Fixes issue mentioned in https://github.com/LawnchairLauncher/lawnicons/pull/2759#pullrequestreview-2908090661
&check; Bug fix (non-breaking change which fixes an issue)  
&cross; General change (non-breaking change that doesn't fit the above categories, such as copyediting)
> Clean up trailing spaces

- CONTRIBUTING.md
> Link to common issues in the Lawnicons guidelines

- app/assets/appfilter.xml
- svgs/rune.svg
Add icon for Rune
[Rune](https://github.com/Losses/rune) (`ci.not.rune`)
> Add icon for Rune

- .github/ISSUE_TEMPLATE/general_discussion.yml
From time to time, we are informed about bugs that have already been fixed, as people tend to focus on the release version. To minimize this, we should invite them to download the latest dev build and evaluate the relevance of their issue.
> Small update to the general issue template

- .github/workflows/build_debug_apk.yml
Added order to the Lawnicons Nightly file name and removed what looks superfluous.
**Before**
```
Lawnicons.Debug.develop.Nightly-CI_7215-39bc101.apk
```
**After**
```
Lawnicons.Nightly(develop-39bc101).apk
```
> Neat Lawnicons Nightly apk name

- .github/PULL_REQUEST_TEMPLATE/icon_addition.md
> Update for the icon addition template

- CONTRIBUTING.md
> Reworded guide for adding icons

- README.md
I made a label for icons that appear thanks to other contributors. Everyone will be able to see how many additional icons have been added.
> Minor link change

- CONTRIBUTING.md
To make it clearer to people what to click.
> Video on the fundamentals

- app/assets/appfilter.xml
Reverts LawnchairLauncher/lawnicons#2997
> Revert "+9 links"

- CONTRIBUTING.md
Common issues are highlighted better.
> Minor changes to the Lawnicons guidelines
